MDScreen:
    name: "splash"
    MDFloatLayout:
        md_bg_color: 255/255, 170/255, 5/255, 1
        Image:
            source: "demo.png"
            size_hint: 0.9, 0.9
            pos_hint: {'center_x': 0.5,'center_y': 0.6}
        MDLabel:
            text: "Dice"
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            halign: 'center'
            theme_text_color: 'Custom'
            text_color: 1,1,1,1
            font_size: "35sp"
            font_name: "3.ttf"